language: java
sudo: false # faster builds
script:
jdk:
  - oraclejdk8
script: 
    - mvn -B -e clean compile test 
after_success:
    - gpg --import gpg/encrypted_key.gpg
    - if [ "$TRAVIS_BRANCH" = "master" ] && [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn package deploy -B -e --settings settings.xml; fi
