name: build

on: [push]

jobs:
  build:
    name: Verify Java ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11', '15' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt-hotspot'
      - name: Cache Maven Wrapper
        uses: actions/cache@v2
        with:
          path: ./.mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('./.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-maven-wrapper
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Verify
        # Skip formatting check on all but JDK 11, because formatter does not support 1.8 and there's no point to running this check on every JDK
        run: ./mvnw --batch-mode -Dspotless.check.skip=${{ matrix.java != '11' }} verify
