name: publish-gradle-plugin

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Gradle Plugin Portal
    runs-on: ubuntu-latest
    environment: Gradle Plugin Portal
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: 11
          distribution: temurin

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Gradle Release
        env:
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

        run: |
          cd gradle-plugin/ && ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

