name: publish

on:
  push:
    branches:
      - sign

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Cache Maven Wrapper
        uses: actions/cache@v2
        with:
          path: ./.mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('./.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-maven-wrapper

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-repo

      - name: Build
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn --batch-mode -DskipTests -Prelease verify
